// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {core} from '../models';
import {config} from '../models';

export function GenerateDeviceCode():Promise<string>;

export function GetAvailableAddresses():Promise<Array<core.Address>>;

export function GetConfig():Promise<config.Config>;

export function GetPairedDevices():Promise<Array<core.DeviceInfo>>;

export function IsSetupComplete():Promise<boolean>;

export function Run():Promise<void>;

export function SaveConfig(arg1:config.Config):Promise<void>;

export function WasSetup():Promise<boolean>;
