// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAvailableAddresses() {
  return window['go']['app']['App']['GetAvailableAddresses']();
}

export function GetPairedDevices() {
  return window['go']['app']['App']['GetPairedDevices']();
}

export function Run() {
  return window['go']['app']['App']['Run']();
}
