// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {core} from '../models';

export function GetAvailableAddresses():Promise<Array<core.DeviceAddress>>;

export function GetPairedDevices():Promise<Array<core.DeviceInfo>>;

export function Run():Promise<void>;
