// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {pair} from '../models';
import {config} from '../models';
import {pbuf} from '../models';
import {service} from '../models';
import {device} from '../models';

export function AskDirectory():Promise<string>;

export function GenerateDeviceCode():Promise<string>;

export function GetAndSendFiles(arg1:pair.Pair):Promise<void>;

export function GetConfig():Promise<config.Config>;

export function GetPairedDeviceSysInfo(arg1:pair.Pair):Promise<pbuf.SysInfo>;

export function GetPairedDevices():Promise<Array<pair.Pair>>;

export function GetServices():Promise<Array<service.Service>>;

export function GetThisDeviceSysInfo():Promise<pbuf.SysInfo>;

export function HandlePairRequest(arg1:pbuf.PairRequest):Promise<number>;

export function HandlePairResponse(arg1:pbuf.PairResponse):Promise<number>;

export function IsSetupComplete():Promise<boolean>;

export function RequestPair(arg1:device.DeviceInfo,arg2:Array<service.Service>):Promise<void>;

export function Run():Promise<void>;

export function SaveConfig(arg1:config.Config):Promise<void>;

export function SearchDevices():Promise<Array<device.DeviceInfo>>;

export function SetupServices():Promise<void>;

export function WasSetup():Promise<boolean>;
