// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AskDirectory() {
  return window['go']['app']['App']['AskDirectory']();
}

export function GenerateDeviceCode() {
  return window['go']['app']['App']['GenerateDeviceCode']();
}

export function GetAndSendFiles(arg1) {
  return window['go']['app']['App']['GetAndSendFiles'](arg1);
}

export function GetConfig() {
  return window['go']['app']['App']['GetConfig']();
}

export function GetPairedDeviceSysInfo(arg1) {
  return window['go']['app']['App']['GetPairedDeviceSysInfo'](arg1);
}

export function GetPairedDevices() {
  return window['go']['app']['App']['GetPairedDevices']();
}

export function GetServices() {
  return window['go']['app']['App']['GetServices']();
}

export function GetThisDeviceSysInfo() {
  return window['go']['app']['App']['GetThisDeviceSysInfo']();
}

export function HandlePairRequest(arg1) {
  return window['go']['app']['App']['HandlePairRequest'](arg1);
}

export function HandlePairResponse(arg1) {
  return window['go']['app']['App']['HandlePairResponse'](arg1);
}

export function IsSetupComplete() {
  return window['go']['app']['App']['IsSetupComplete']();
}

export function RequestPair(arg1, arg2) {
  return window['go']['app']['App']['RequestPair'](arg1, arg2);
}

export function Run() {
  return window['go']['app']['App']['Run']();
}

export function SaveConfig(arg1) {
  return window['go']['app']['App']['SaveConfig'](arg1);
}

export function SearchDevices() {
  return window['go']['app']['App']['SearchDevices']();
}

export function SetupServices() {
  return window['go']['app']['App']['SetupServices']();
}

export function WasSetup() {
  return window['go']['app']['App']['WasSetup']();
}
