// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GenerateDeviceCode() {
  return window['go']['app']['App']['GenerateDeviceCode']();
}

export function GetConfig() {
  return window['go']['app']['App']['GetConfig']();
}

export function GetPairedDevices() {
  return window['go']['app']['App']['GetPairedDevices']();
}

export function IsSetupComplete() {
  return window['go']['app']['App']['IsSetupComplete']();
}

export function Run() {
  return window['go']['app']['App']['Run']();
}

export function SaveConfig(arg1) {
  return window['go']['app']['App']['SaveConfig'](arg1);
}

export function SearchDevices() {
  return window['go']['app']['App']['SearchDevices']();
}

export function WasSetup() {
  return window['go']['app']['App']['WasSetup']();
}
