// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: pair.proto

package pbuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DeviceType int32

const (
	DeviceType_DEVICE_TYPE_UNSPECIFIED DeviceType = 0
	DeviceType_DEVICE_TYPE_MOBILE      DeviceType = 1
	DeviceType_DEVICE_TYPE_DESKTOP     DeviceType = 2
	DeviceType_DEVICE_TYPE_TV          DeviceType = 3
)

// Enum value maps for DeviceType.
var (
	DeviceType_name = map[int32]string{
		0: "DEVICE_TYPE_UNSPECIFIED",
		1: "DEVICE_TYPE_MOBILE",
		2: "DEVICE_TYPE_DESKTOP",
		3: "DEVICE_TYPE_TV",
	}
	DeviceType_value = map[string]int32{
		"DEVICE_TYPE_UNSPECIFIED": 0,
		"DEVICE_TYPE_MOBILE":      1,
		"DEVICE_TYPE_DESKTOP":     2,
		"DEVICE_TYPE_TV":          3,
	}
)

func (x DeviceType) Enum() *DeviceType {
	p := new(DeviceType)
	*p = x
	return p
}

func (x DeviceType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DeviceType) Descriptor() protoreflect.EnumDescriptor {
	return file_pair_proto_enumTypes[0].Descriptor()
}

func (DeviceType) Type() protoreflect.EnumType {
	return &file_pair_proto_enumTypes[0]
}

func (x DeviceType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DeviceType.Descriptor instead.
func (DeviceType) EnumDescriptor() ([]byte, []int) {
	return file_pair_proto_rawDescGZIP(), []int{0}
}

type ServiceCallStatus int32

const (
	ServiceCallStatus_SERVICE_CALL_STATUS_OK           ServiceCallStatus = 0
	ServiceCallStatus_SERVICE_CALL_STATUS_ERROR        ServiceCallStatus = 1
	ServiceCallStatus_SERVICE_CALL_STATUS_UNAUTHORIZED ServiceCallStatus = 2
	ServiceCallStatus_SERVICE_CALL_STATUS_DISABLED     ServiceCallStatus = 3
	ServiceCallStatus_SERVICE_CALL_STATUS_UNKNOWN      ServiceCallStatus = 4
)

// Enum value maps for ServiceCallStatus.
var (
	ServiceCallStatus_name = map[int32]string{
		0: "SERVICE_CALL_STATUS_OK",
		1: "SERVICE_CALL_STATUS_ERROR",
		2: "SERVICE_CALL_STATUS_UNAUTHORIZED",
		3: "SERVICE_CALL_STATUS_DISABLED",
		4: "SERVICE_CALL_STATUS_UNKNOWN",
	}
	ServiceCallStatus_value = map[string]int32{
		"SERVICE_CALL_STATUS_OK":           0,
		"SERVICE_CALL_STATUS_ERROR":        1,
		"SERVICE_CALL_STATUS_UNAUTHORIZED": 2,
		"SERVICE_CALL_STATUS_DISABLED":     3,
		"SERVICE_CALL_STATUS_UNKNOWN":      4,
	}
)

func (x ServiceCallStatus) Enum() *ServiceCallStatus {
	p := new(ServiceCallStatus)
	*p = x
	return p
}

func (x ServiceCallStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ServiceCallStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_pair_proto_enumTypes[1].Descriptor()
}

func (ServiceCallStatus) Type() protoreflect.EnumType {
	return &file_pair_proto_enumTypes[1]
}

func (x ServiceCallStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ServiceCallStatus.Descriptor instead.
func (ServiceCallStatus) EnumDescriptor() ([]byte, []int) {
	return file_pair_proto_rawDescGZIP(), []int{1}
}

type Color struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Color) Reset() {
	*x = Color{}
	mi := &file_pair_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Color) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Color) ProtoMessage() {}

func (x *Color) ProtoReflect() protoreflect.Message {
	mi := &file_pair_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Color.ProtoReflect.Descriptor instead.
func (*Color) Descriptor() ([]byte, []int) {
	return file_pair_proto_rawDescGZIP(), []int{0}
}

func (x *Color) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type DeviceInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type          DeviceType             `protobuf:"varint,3,opt,name=type,proto3,enum=pbuf.v1.DeviceType" json:"type,omitempty"`
	Color         *Color                 `protobuf:"bytes,4,opt,name=color,proto3" json:"color,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceInfo) Reset() {
	*x = DeviceInfo{}
	mi := &file_pair_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceInfo) ProtoMessage() {}

func (x *DeviceInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pair_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceInfo.ProtoReflect.Descriptor instead.
func (*DeviceInfo) Descriptor() ([]byte, []int) {
	return file_pair_proto_rawDescGZIP(), []int{1}
}

func (x *DeviceInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DeviceInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DeviceInfo) GetType() DeviceType {
	if x != nil {
		return x.Type
	}
	return DeviceType_DEVICE_TYPE_UNSPECIFIED
}

func (x *DeviceInfo) GetColor() *Color {
	if x != nil {
		return x.Color
	}
	return nil
}

type DeviceDetails struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Certificate   []byte                 `protobuf:"bytes,1,opt,name=certificate,proto3" json:"certificate,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type          DeviceType             `protobuf:"varint,3,opt,name=type,proto3,enum=pbuf.v1.DeviceType" json:"type,omitempty"`
	Color         *Color                 `protobuf:"bytes,4,opt,name=color,proto3" json:"color,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceDetails) Reset() {
	*x = DeviceDetails{}
	mi := &file_pair_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceDetails) ProtoMessage() {}

func (x *DeviceDetails) ProtoReflect() protoreflect.Message {
	mi := &file_pair_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceDetails.ProtoReflect.Descriptor instead.
func (*DeviceDetails) Descriptor() ([]byte, []int) {
	return file_pair_proto_rawDescGZIP(), []int{2}
}

func (x *DeviceDetails) GetCertificate() []byte {
	if x != nil {
		return x.Certificate
	}
	return nil
}

func (x *DeviceDetails) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DeviceDetails) GetType() DeviceType {
	if x != nil {
		return x.Type
	}
	return DeviceType_DEVICE_TYPE_UNSPECIFIED
}

func (x *DeviceDetails) GetColor() *Color {
	if x != nil {
		return x.Color
	}
	return nil
}

type RequestPairRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         []byte                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Details       *DeviceDetails         `protobuf:"bytes,2,opt,name=details,proto3" json:"details,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestPairRequest) Reset() {
	*x = RequestPairRequest{}
	mi := &file_pair_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestPairRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestPairRequest) ProtoMessage() {}

func (x *RequestPairRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pair_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestPairRequest.ProtoReflect.Descriptor instead.
func (*RequestPairRequest) Descriptor() ([]byte, []int) {
	return file_pair_proto_rawDescGZIP(), []int{3}
}

func (x *RequestPairRequest) GetToken() []byte {
	if x != nil {
		return x.Token
	}
	return nil
}

func (x *RequestPairRequest) GetDetails() *DeviceDetails {
	if x != nil {
		return x.Details
	}
	return nil
}

type RequestPairResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         []byte                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Accepted      bool                   `protobuf:"varint,2,opt,name=accepted,proto3" json:"accepted,omitempty"`
	Details       *DeviceDetails         `protobuf:"bytes,3,opt,name=details,proto3" json:"details,omitempty"`
	Reason        string                 `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestPairResponse) Reset() {
	*x = RequestPairResponse{}
	mi := &file_pair_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestPairResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestPairResponse) ProtoMessage() {}

func (x *RequestPairResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pair_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestPairResponse.ProtoReflect.Descriptor instead.
func (*RequestPairResponse) Descriptor() ([]byte, []int) {
	return file_pair_proto_rawDescGZIP(), []int{4}
}

func (x *RequestPairResponse) GetToken() []byte {
	if x != nil {
		return x.Token
	}
	return nil
}

func (x *RequestPairResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *RequestPairResponse) GetDetails() *DeviceDetails {
	if x != nil {
		return x.Details
	}
	return nil
}

func (x *RequestPairResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type GetDetailsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDetailsRequest) Reset() {
	*x = GetDetailsRequest{}
	mi := &file_pair_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDetailsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDetailsRequest) ProtoMessage() {}

func (x *GetDetailsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pair_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDetailsRequest.ProtoReflect.Descriptor instead.
func (*GetDetailsRequest) Descriptor() ([]byte, []int) {
	return file_pair_proto_rawDescGZIP(), []int{5}
}

type GetDetailsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Details       *DeviceDetails         `protobuf:"bytes,1,opt,name=details,proto3" json:"details,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDetailsResponse) Reset() {
	*x = GetDetailsResponse{}
	mi := &file_pair_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDetailsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDetailsResponse) ProtoMessage() {}

func (x *GetDetailsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pair_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDetailsResponse.ProtoReflect.Descriptor instead.
func (*GetDetailsResponse) Descriptor() ([]byte, []int) {
	return file_pair_proto_rawDescGZIP(), []int{6}
}

func (x *GetDetailsResponse) GetDetails() *DeviceDetails {
	if x != nil {
		return x.Details
	}
	return nil
}

type GetInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInfoRequest) Reset() {
	*x = GetInfoRequest{}
	mi := &file_pair_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInfoRequest) ProtoMessage() {}

func (x *GetInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pair_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInfoRequest.ProtoReflect.Descriptor instead.
func (*GetInfoRequest) Descriptor() ([]byte, []int) {
	return file_pair_proto_rawDescGZIP(), []int{7}
}

type GetInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Info          *DeviceInfo            `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInfoResponse) Reset() {
	*x = GetInfoResponse{}
	mi := &file_pair_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInfoResponse) ProtoMessage() {}

func (x *GetInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pair_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInfoResponse.ProtoReflect.Descriptor instead.
func (*GetInfoResponse) Descriptor() ([]byte, []int) {
	return file_pair_proto_rawDescGZIP(), []int{8}
}

func (x *GetInfoResponse) GetInfo() *DeviceInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

type SysInfo struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	HostName        string                 `protobuf:"bytes,1,opt,name=hostName,proto3" json:"hostName,omitempty"`
	Os              string                 `protobuf:"bytes,2,opt,name=os,proto3" json:"os,omitempty"`
	Platform        string                 `protobuf:"bytes,3,opt,name=platform,proto3" json:"platform,omitempty"`
	MemTotal        uint64                 `protobuf:"varint,4,opt,name=memTotal,proto3" json:"memTotal,omitempty"`
	MemUsed         uint64                 `protobuf:"varint,5,opt,name=memUsed,proto3" json:"memUsed,omitempty"`
	DiskTotal       uint64                 `protobuf:"varint,6,opt,name=diskTotal,proto3" json:"diskTotal,omitempty"`
	DiskUsed        uint64                 `protobuf:"varint,7,opt,name=diskUsed,proto3" json:"diskUsed,omitempty"`
	BatteryCharging bool                   `protobuf:"varint,8,opt,name=batteryCharging,proto3" json:"batteryCharging,omitempty"`
	BatteryPercent  float64                `protobuf:"fixed64,9,opt,name=batteryPercent,proto3" json:"batteryPercent,omitempty"`
	CpuUsage        float64                `protobuf:"fixed64,10,opt,name=cpuUsage,proto3" json:"cpuUsage,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SysInfo) Reset() {
	*x = SysInfo{}
	mi := &file_pair_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SysInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SysInfo) ProtoMessage() {}

func (x *SysInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pair_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SysInfo.ProtoReflect.Descriptor instead.
func (*SysInfo) Descriptor() ([]byte, []int) {
	return file_pair_proto_rawDescGZIP(), []int{9}
}

func (x *SysInfo) GetHostName() string {
	if x != nil {
		return x.HostName
	}
	return ""
}

func (x *SysInfo) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *SysInfo) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *SysInfo) GetMemTotal() uint64 {
	if x != nil {
		return x.MemTotal
	}
	return 0
}

func (x *SysInfo) GetMemUsed() uint64 {
	if x != nil {
		return x.MemUsed
	}
	return 0
}

func (x *SysInfo) GetDiskTotal() uint64 {
	if x != nil {
		return x.DiskTotal
	}
	return 0
}

func (x *SysInfo) GetDiskUsed() uint64 {
	if x != nil {
		return x.DiskUsed
	}
	return 0
}

func (x *SysInfo) GetBatteryCharging() bool {
	if x != nil {
		return x.BatteryCharging
	}
	return false
}

func (x *SysInfo) GetBatteryPercent() float64 {
	if x != nil {
		return x.BatteryPercent
	}
	return 0
}

func (x *SysInfo) GetCpuUsage() float64 {
	if x != nil {
		return x.CpuUsage
	}
	return 0
}

type GetSysInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         []byte                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSysInfoRequest) Reset() {
	*x = GetSysInfoRequest{}
	mi := &file_pair_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSysInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSysInfoRequest) ProtoMessage() {}

func (x *GetSysInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pair_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSysInfoRequest.ProtoReflect.Descriptor instead.
func (*GetSysInfoRequest) Descriptor() ([]byte, []int) {
	return file_pair_proto_rawDescGZIP(), []int{10}
}

func (x *GetSysInfoRequest) GetToken() []byte {
	if x != nil {
		return x.Token
	}
	return nil
}

type GetSysInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        ServiceCallStatus      `protobuf:"varint,1,opt,name=status,proto3,enum=pbuf.v1.ServiceCallStatus" json:"status,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Info          *SysInfo               `protobuf:"bytes,3,opt,name=info,proto3" json:"info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSysInfoResponse) Reset() {
	*x = GetSysInfoResponse{}
	mi := &file_pair_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSysInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSysInfoResponse) ProtoMessage() {}

func (x *GetSysInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pair_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSysInfoResponse.ProtoReflect.Descriptor instead.
func (*GetSysInfoResponse) Descriptor() ([]byte, []int) {
	return file_pair_proto_rawDescGZIP(), []int{11}
}

func (x *GetSysInfoResponse) GetStatus() ServiceCallStatus {
	if x != nil {
		return x.Status
	}
	return ServiceCallStatus_SERVICE_CALL_STATUS_OK
}

func (x *GetSysInfoResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *GetSysInfoResponse) GetInfo() *SysInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

type InitialSendFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      *FileMetadata          `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	SenderInfo    *DeviceInfo            `protobuf:"bytes,2,opt,name=sender_info,json=senderInfo,proto3" json:"sender_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitialSendFileRequest) Reset() {
	*x = InitialSendFileRequest{}
	mi := &file_pair_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitialSendFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitialSendFileRequest) ProtoMessage() {}

func (x *InitialSendFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pair_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitialSendFileRequest.ProtoReflect.Descriptor instead.
func (*InitialSendFileRequest) Descriptor() ([]byte, []int) {
	return file_pair_proto_rawDescGZIP(), []int{12}
}

func (x *InitialSendFileRequest) GetMetadata() *FileMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *InitialSendFileRequest) GetSenderInfo() *DeviceInfo {
	if x != nil {
		return x.SenderInfo
	}
	return nil
}

type FileMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Size          int64                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	Mode          int32                  `protobuf:"varint,3,opt,name=mode,proto3" json:"mode,omitempty"` // File permissions
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileMetadata) Reset() {
	*x = FileMetadata{}
	mi := &file_pair_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileMetadata) ProtoMessage() {}

func (x *FileMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_pair_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileMetadata.ProtoReflect.Descriptor instead.
func (*FileMetadata) Descriptor() ([]byte, []int) {
	return file_pair_proto_rawDescGZIP(), []int{13}
}

func (x *FileMetadata) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FileMetadata) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *FileMetadata) GetMode() int32 {
	if x != nil {
		return x.Mode
	}
	return 0
}

type FileChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       []byte                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileChunk) Reset() {
	*x = FileChunk{}
	mi := &file_pair_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileChunk) ProtoMessage() {}

func (x *FileChunk) ProtoReflect() protoreflect.Message {
	mi := &file_pair_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileChunk.ProtoReflect.Descriptor instead.
func (*FileChunk) Descriptor() ([]byte, []int) {
	return file_pair_proto_rawDescGZIP(), []int{14}
}

func (x *FileChunk) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

type SendFileRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Data:
	//
	//	*SendFileRequest_InitialRequest
	//	*SendFileRequest_Chunk
	Data          isSendFileRequest_Data `protobuf_oneof:"data"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendFileRequest) Reset() {
	*x = SendFileRequest{}
	mi := &file_pair_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendFileRequest) ProtoMessage() {}

func (x *SendFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pair_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendFileRequest.ProtoReflect.Descriptor instead.
func (*SendFileRequest) Descriptor() ([]byte, []int) {
	return file_pair_proto_rawDescGZIP(), []int{15}
}

func (x *SendFileRequest) GetData() isSendFileRequest_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *SendFileRequest) GetInitialRequest() *InitialSendFileRequest {
	if x != nil {
		if x, ok := x.Data.(*SendFileRequest_InitialRequest); ok {
			return x.InitialRequest
		}
	}
	return nil
}

func (x *SendFileRequest) GetChunk() *FileChunk {
	if x != nil {
		if x, ok := x.Data.(*SendFileRequest_Chunk); ok {
			return x.Chunk
		}
	}
	return nil
}

type isSendFileRequest_Data interface {
	isSendFileRequest_Data()
}

type SendFileRequest_InitialRequest struct {
	InitialRequest *InitialSendFileRequest `protobuf:"bytes,1,opt,name=initial_request,json=initialRequest,proto3,oneof"`
}

type SendFileRequest_Chunk struct {
	Chunk *FileChunk `protobuf:"bytes,2,opt,name=chunk,proto3,oneof"`
}

func (*SendFileRequest_InitialRequest) isSendFileRequest_Data() {}

func (*SendFileRequest_Chunk) isSendFileRequest_Data() {}

type SendFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        ServiceCallStatus      `protobuf:"varint,1,opt,name=status,proto3,enum=pbuf.v1.ServiceCallStatus" json:"status,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendFileResponse) Reset() {
	*x = SendFileResponse{}
	mi := &file_pair_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendFileResponse) ProtoMessage() {}

func (x *SendFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pair_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendFileResponse.ProtoReflect.Descriptor instead.
func (*SendFileResponse) Descriptor() ([]byte, []int) {
	return file_pair_proto_rawDescGZIP(), []int{16}
}

func (x *SendFileResponse) GetStatus() ServiceCallStatus {
	if x != nil {
		return x.Status
	}
	return ServiceCallStatus_SERVICE_CALL_STATUS_OK
}

func (x *SendFileResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

var File_pair_proto protoreflect.FileDescriptor

const file_pair_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"pair.proto\x12\apbuf.v1\"\x1b\n" +
	"\x05Color\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\x7f\n" +
	"\n" +
	"DeviceInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12'\n" +
	"\x04type\x18\x03 \x01(\x0e2\x13.pbuf.v1.DeviceTypeR\x04type\x12$\n" +
	"\x05color\x18\x04 \x01(\v2\x0e.pbuf.v1.ColorR\x05color\"\x94\x01\n" +
	"\rDeviceDetails\x12 \n" +
	"\vcertificate\x18\x01 \x01(\fR\vcertificate\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12'\n" +
	"\x04type\x18\x03 \x01(\x0e2\x13.pbuf.v1.DeviceTypeR\x04type\x12$\n" +
	"\x05color\x18\x04 \x01(\v2\x0e.pbuf.v1.ColorR\x05color\"\\\n" +
	"\x12RequestPairRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\fR\x05token\x120\n" +
	"\adetails\x18\x02 \x01(\v2\x16.pbuf.v1.DeviceDetailsR\adetails\"\x91\x01\n" +
	"\x13RequestPairResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\fR\x05token\x12\x1a\n" +
	"\baccepted\x18\x02 \x01(\bR\baccepted\x120\n" +
	"\adetails\x18\x03 \x01(\v2\x16.pbuf.v1.DeviceDetailsR\adetails\x12\x16\n" +
	"\x06reason\x18\x04 \x01(\tR\x06reason\"\x13\n" +
	"\x11GetDetailsRequest\"F\n" +
	"\x12GetDetailsResponse\x120\n" +
	"\adetails\x18\x01 \x01(\v2\x16.pbuf.v1.DeviceDetailsR\adetails\"\x10\n" +
	"\x0eGetInfoRequest\":\n" +
	"\x0fGetInfoResponse\x12'\n" +
	"\x04info\x18\x01 \x01(\v2\x13.pbuf.v1.DeviceInfoR\x04info\"\xaf\x02\n" +
	"\aSysInfo\x12\x1a\n" +
	"\bhostName\x18\x01 \x01(\tR\bhostName\x12\x0e\n" +
	"\x02os\x18\x02 \x01(\tR\x02os\x12\x1a\n" +
	"\bplatform\x18\x03 \x01(\tR\bplatform\x12\x1a\n" +
	"\bmemTotal\x18\x04 \x01(\x04R\bmemTotal\x12\x18\n" +
	"\amemUsed\x18\x05 \x01(\x04R\amemUsed\x12\x1c\n" +
	"\tdiskTotal\x18\x06 \x01(\x04R\tdiskTotal\x12\x1a\n" +
	"\bdiskUsed\x18\a \x01(\x04R\bdiskUsed\x12(\n" +
	"\x0fbatteryCharging\x18\b \x01(\bR\x0fbatteryCharging\x12&\n" +
	"\x0ebatteryPercent\x18\t \x01(\x01R\x0ebatteryPercent\x12\x1a\n" +
	"\bcpuUsage\x18\n" +
	" \x01(\x01R\bcpuUsage\")\n" +
	"\x11GetSysInfoRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\fR\x05token\"\x80\x01\n" +
	"\x12GetSysInfoResponse\x122\n" +
	"\x06status\x18\x01 \x01(\x0e2\x1a.pbuf.v1.ServiceCallStatusR\x06status\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12$\n" +
	"\x04info\x18\x03 \x01(\v2\x10.pbuf.v1.SysInfoR\x04info\"\x81\x01\n" +
	"\x16InitialSendFileRequest\x121\n" +
	"\bmetadata\x18\x01 \x01(\v2\x15.pbuf.v1.FileMetadataR\bmetadata\x124\n" +
	"\vsender_info\x18\x02 \x01(\v2\x13.pbuf.v1.DeviceInfoR\n" +
	"senderInfo\"J\n" +
	"\fFileMetadata\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x03R\x04size\x12\x12\n" +
	"\x04mode\x18\x03 \x01(\x05R\x04mode\"%\n" +
	"\tFileChunk\x12\x18\n" +
	"\acontent\x18\x01 \x01(\fR\acontent\"\x91\x01\n" +
	"\x0fSendFileRequest\x12J\n" +
	"\x0finitial_request\x18\x01 \x01(\v2\x1f.pbuf.v1.InitialSendFileRequestH\x00R\x0einitialRequest\x12*\n" +
	"\x05chunk\x18\x02 \x01(\v2\x12.pbuf.v1.FileChunkH\x00R\x05chunkB\x06\n" +
	"\x04data\"X\n" +
	"\x10SendFileResponse\x122\n" +
	"\x06status\x18\x01 \x01(\x0e2\x1a.pbuf.v1.ServiceCallStatusR\x06status\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg*n\n" +
	"\n" +
	"DeviceType\x12\x1b\n" +
	"\x17DEVICE_TYPE_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12DEVICE_TYPE_MOBILE\x10\x01\x12\x17\n" +
	"\x13DEVICE_TYPE_DESKTOP\x10\x02\x12\x12\n" +
	"\x0eDEVICE_TYPE_TV\x10\x03*\xb7\x01\n" +
	"\x11ServiceCallStatus\x12\x1a\n" +
	"\x16SERVICE_CALL_STATUS_OK\x10\x00\x12\x1d\n" +
	"\x19SERVICE_CALL_STATUS_ERROR\x10\x01\x12$\n" +
	" SERVICE_CALL_STATUS_UNAUTHORIZED\x10\x02\x12 \n" +
	"\x1cSERVICE_CALL_STATUS_DISABLED\x10\x03\x12\x1f\n" +
	"\x1bSERVICE_CALL_STATUS_UNKNOWN\x10\x042\xa3\x02\n" +
	"\vAlatService\x12H\n" +
	"\vRequestPair\x12\x1b.pbuf.v1.RequestPairRequest\x1a\x1c.pbuf.v1.RequestPairResponse\x12E\n" +
	"\n" +
	"GetDetails\x12\x1a.pbuf.v1.GetDetailsRequest\x1a\x1b.pbuf.v1.GetDetailsResponse\x12<\n" +
	"\aGetInfo\x12\x17.pbuf.v1.GetInfoRequest\x1a\x18.pbuf.v1.GetInfoResponse\x12E\n" +
	"\n" +
	"GetSysInfo\x12\x1a.pbuf.v1.GetSysInfoRequest\x1a\x1b.pbuf.v1.GetSysInfoResponse2T\n" +
	"\x0fFileSendService\x12A\n" +
	"\bSendFile\x12\x18.pbuf.v1.SendFileRequest\x1a\x19.pbuf.v1.SendFileResponse(\x01B\x0fZ\ralat/pkg/pbufb\x06proto3"

var (
	file_pair_proto_rawDescOnce sync.Once
	file_pair_proto_rawDescData []byte
)

func file_pair_proto_rawDescGZIP() []byte {
	file_pair_proto_rawDescOnce.Do(func() {
		file_pair_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pair_proto_rawDesc), len(file_pair_proto_rawDesc)))
	})
	return file_pair_proto_rawDescData
}

var file_pair_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_pair_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_pair_proto_goTypes = []any{
	(DeviceType)(0),                // 0: pbuf.v1.DeviceType
	(ServiceCallStatus)(0),         // 1: pbuf.v1.ServiceCallStatus
	(*Color)(nil),                  // 2: pbuf.v1.Color
	(*DeviceInfo)(nil),             // 3: pbuf.v1.DeviceInfo
	(*DeviceDetails)(nil),          // 4: pbuf.v1.DeviceDetails
	(*RequestPairRequest)(nil),     // 5: pbuf.v1.RequestPairRequest
	(*RequestPairResponse)(nil),    // 6: pbuf.v1.RequestPairResponse
	(*GetDetailsRequest)(nil),      // 7: pbuf.v1.GetDetailsRequest
	(*GetDetailsResponse)(nil),     // 8: pbuf.v1.GetDetailsResponse
	(*GetInfoRequest)(nil),         // 9: pbuf.v1.GetInfoRequest
	(*GetInfoResponse)(nil),        // 10: pbuf.v1.GetInfoResponse
	(*SysInfo)(nil),                // 11: pbuf.v1.SysInfo
	(*GetSysInfoRequest)(nil),      // 12: pbuf.v1.GetSysInfoRequest
	(*GetSysInfoResponse)(nil),     // 13: pbuf.v1.GetSysInfoResponse
	(*InitialSendFileRequest)(nil), // 14: pbuf.v1.InitialSendFileRequest
	(*FileMetadata)(nil),           // 15: pbuf.v1.FileMetadata
	(*FileChunk)(nil),              // 16: pbuf.v1.FileChunk
	(*SendFileRequest)(nil),        // 17: pbuf.v1.SendFileRequest
	(*SendFileResponse)(nil),       // 18: pbuf.v1.SendFileResponse
}
var file_pair_proto_depIdxs = []int32{
	0,  // 0: pbuf.v1.DeviceInfo.type:type_name -> pbuf.v1.DeviceType
	2,  // 1: pbuf.v1.DeviceInfo.color:type_name -> pbuf.v1.Color
	0,  // 2: pbuf.v1.DeviceDetails.type:type_name -> pbuf.v1.DeviceType
	2,  // 3: pbuf.v1.DeviceDetails.color:type_name -> pbuf.v1.Color
	4,  // 4: pbuf.v1.RequestPairRequest.details:type_name -> pbuf.v1.DeviceDetails
	4,  // 5: pbuf.v1.RequestPairResponse.details:type_name -> pbuf.v1.DeviceDetails
	4,  // 6: pbuf.v1.GetDetailsResponse.details:type_name -> pbuf.v1.DeviceDetails
	3,  // 7: pbuf.v1.GetInfoResponse.info:type_name -> pbuf.v1.DeviceInfo
	1,  // 8: pbuf.v1.GetSysInfoResponse.status:type_name -> pbuf.v1.ServiceCallStatus
	11, // 9: pbuf.v1.GetSysInfoResponse.info:type_name -> pbuf.v1.SysInfo
	15, // 10: pbuf.v1.InitialSendFileRequest.metadata:type_name -> pbuf.v1.FileMetadata
	3,  // 11: pbuf.v1.InitialSendFileRequest.sender_info:type_name -> pbuf.v1.DeviceInfo
	14, // 12: pbuf.v1.SendFileRequest.initial_request:type_name -> pbuf.v1.InitialSendFileRequest
	16, // 13: pbuf.v1.SendFileRequest.chunk:type_name -> pbuf.v1.FileChunk
	1,  // 14: pbuf.v1.SendFileResponse.status:type_name -> pbuf.v1.ServiceCallStatus
	5,  // 15: pbuf.v1.AlatService.RequestPair:input_type -> pbuf.v1.RequestPairRequest
	7,  // 16: pbuf.v1.AlatService.GetDetails:input_type -> pbuf.v1.GetDetailsRequest
	9,  // 17: pbuf.v1.AlatService.GetInfo:input_type -> pbuf.v1.GetInfoRequest
	12, // 18: pbuf.v1.AlatService.GetSysInfo:input_type -> pbuf.v1.GetSysInfoRequest
	17, // 19: pbuf.v1.FileSendService.SendFile:input_type -> pbuf.v1.SendFileRequest
	6,  // 20: pbuf.v1.AlatService.RequestPair:output_type -> pbuf.v1.RequestPairResponse
	8,  // 21: pbuf.v1.AlatService.GetDetails:output_type -> pbuf.v1.GetDetailsResponse
	10, // 22: pbuf.v1.AlatService.GetInfo:output_type -> pbuf.v1.GetInfoResponse
	13, // 23: pbuf.v1.AlatService.GetSysInfo:output_type -> pbuf.v1.GetSysInfoResponse
	18, // 24: pbuf.v1.FileSendService.SendFile:output_type -> pbuf.v1.SendFileResponse
	20, // [20:25] is the sub-list for method output_type
	15, // [15:20] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_pair_proto_init() }
func file_pair_proto_init() {
	if File_pair_proto != nil {
		return
	}
	file_pair_proto_msgTypes[15].OneofWrappers = []any{
		(*SendFileRequest_InitialRequest)(nil),
		(*SendFileRequest_Chunk)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pair_proto_rawDesc), len(file_pair_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_pair_proto_goTypes,
		DependencyIndexes: file_pair_proto_depIdxs,
		EnumInfos:         file_pair_proto_enumTypes,
		MessageInfos:      file_pair_proto_msgTypes,
	}.Build()
	File_pair_proto = out.File
	file_pair_proto_goTypes = nil
	file_pair_proto_depIdxs = nil
}
