// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.21.12
// source: pair.proto

package pbuf

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AlatService_RequestPair_FullMethodName = "/pbuf.v1.AlatService/RequestPair"
	AlatService_GetDetails_FullMethodName  = "/pbuf.v1.AlatService/GetDetails"
	AlatService_GetInfo_FullMethodName     = "/pbuf.v1.AlatService/GetInfo"
)

// AlatServiceClient is the client API for AlatService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AlatServiceClient interface {
	RequestPair(ctx context.Context, in *RequestPairRequest, opts ...grpc.CallOption) (*RequestPairResponse, error)
	GetDetails(ctx context.Context, in *GetDetailsRequest, opts ...grpc.CallOption) (*GetDetailsResponse, error)
	GetInfo(ctx context.Context, in *GetInfoRequest, opts ...grpc.CallOption) (*GetInfoResponse, error)
}

type alatServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAlatServiceClient(cc grpc.ClientConnInterface) AlatServiceClient {
	return &alatServiceClient{cc}
}

func (c *alatServiceClient) RequestPair(ctx context.Context, in *RequestPairRequest, opts ...grpc.CallOption) (*RequestPairResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RequestPairResponse)
	err := c.cc.Invoke(ctx, AlatService_RequestPair_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *alatServiceClient) GetDetails(ctx context.Context, in *GetDetailsRequest, opts ...grpc.CallOption) (*GetDetailsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDetailsResponse)
	err := c.cc.Invoke(ctx, AlatService_GetDetails_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *alatServiceClient) GetInfo(ctx context.Context, in *GetInfoRequest, opts ...grpc.CallOption) (*GetInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetInfoResponse)
	err := c.cc.Invoke(ctx, AlatService_GetInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AlatServiceServer is the server API for AlatService service.
// All implementations must embed UnimplementedAlatServiceServer
// for forward compatibility.
type AlatServiceServer interface {
	RequestPair(context.Context, *RequestPairRequest) (*RequestPairResponse, error)
	GetDetails(context.Context, *GetDetailsRequest) (*GetDetailsResponse, error)
	GetInfo(context.Context, *GetInfoRequest) (*GetInfoResponse, error)
	mustEmbedUnimplementedAlatServiceServer()
}

// UnimplementedAlatServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAlatServiceServer struct{}

func (UnimplementedAlatServiceServer) RequestPair(context.Context, *RequestPairRequest) (*RequestPairResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RequestPair not implemented")
}
func (UnimplementedAlatServiceServer) GetDetails(context.Context, *GetDetailsRequest) (*GetDetailsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDetails not implemented")
}
func (UnimplementedAlatServiceServer) GetInfo(context.Context, *GetInfoRequest) (*GetInfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetInfo not implemented")
}
func (UnimplementedAlatServiceServer) mustEmbedUnimplementedAlatServiceServer() {}
func (UnimplementedAlatServiceServer) testEmbeddedByValue()                     {}

// UnsafeAlatServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AlatServiceServer will
// result in compilation errors.
type UnsafeAlatServiceServer interface {
	mustEmbedUnimplementedAlatServiceServer()
}

func RegisterAlatServiceServer(s grpc.ServiceRegistrar, srv AlatServiceServer) {
	// If the following call panics, it indicates UnimplementedAlatServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AlatService_ServiceDesc, srv)
}

func _AlatService_RequestPair_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestPairRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlatServiceServer).RequestPair(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AlatService_RequestPair_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlatServiceServer).RequestPair(ctx, req.(*RequestPairRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AlatService_GetDetails_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDetailsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlatServiceServer).GetDetails(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AlatService_GetDetails_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlatServiceServer).GetDetails(ctx, req.(*GetDetailsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AlatService_GetInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlatServiceServer).GetInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AlatService_GetInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlatServiceServer).GetInfo(ctx, req.(*GetInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AlatService_ServiceDesc is the grpc.ServiceDesc for AlatService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AlatService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pbuf.v1.AlatService",
	HandlerType: (*AlatServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RequestPair",
			Handler:    _AlatService_RequestPair_Handler,
		},
		{
			MethodName: "GetDetails",
			Handler:    _AlatService_GetDetails_Handler,
		},
		{
			MethodName: "GetInfo",
			Handler:    _AlatService_GetInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pair.proto",
}

const (
	SysInfoService_GetSysInfo_FullMethodName = "/pbuf.v1.SysInfoService/GetSysInfo"
)

// SysInfoServiceClient is the client API for SysInfoService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SysInfoServiceClient interface {
	GetSysInfo(ctx context.Context, in *GetSysInfoRequest, opts ...grpc.CallOption) (*GetSysInfoResponse, error)
}

type sysInfoServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSysInfoServiceClient(cc grpc.ClientConnInterface) SysInfoServiceClient {
	return &sysInfoServiceClient{cc}
}

func (c *sysInfoServiceClient) GetSysInfo(ctx context.Context, in *GetSysInfoRequest, opts ...grpc.CallOption) (*GetSysInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSysInfoResponse)
	err := c.cc.Invoke(ctx, SysInfoService_GetSysInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SysInfoServiceServer is the server API for SysInfoService service.
// All implementations must embed UnimplementedSysInfoServiceServer
// for forward compatibility.
type SysInfoServiceServer interface {
	GetSysInfo(context.Context, *GetSysInfoRequest) (*GetSysInfoResponse, error)
	mustEmbedUnimplementedSysInfoServiceServer()
}

// UnimplementedSysInfoServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSysInfoServiceServer struct{}

func (UnimplementedSysInfoServiceServer) GetSysInfo(context.Context, *GetSysInfoRequest) (*GetSysInfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSysInfo not implemented")
}
func (UnimplementedSysInfoServiceServer) mustEmbedUnimplementedSysInfoServiceServer() {}
func (UnimplementedSysInfoServiceServer) testEmbeddedByValue()                        {}

// UnsafeSysInfoServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SysInfoServiceServer will
// result in compilation errors.
type UnsafeSysInfoServiceServer interface {
	mustEmbedUnimplementedSysInfoServiceServer()
}

func RegisterSysInfoServiceServer(s grpc.ServiceRegistrar, srv SysInfoServiceServer) {
	// If the following call panics, it indicates UnimplementedSysInfoServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SysInfoService_ServiceDesc, srv)
}

func _SysInfoService_GetSysInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSysInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SysInfoServiceServer).GetSysInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SysInfoService_GetSysInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SysInfoServiceServer).GetSysInfo(ctx, req.(*GetSysInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SysInfoService_ServiceDesc is the grpc.ServiceDesc for SysInfoService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SysInfoService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pbuf.v1.SysInfoService",
	HandlerType: (*SysInfoServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetSysInfo",
			Handler:    _SysInfoService_GetSysInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pair.proto",
}

const (
	FileSendService_SendFile_FullMethodName = "/pbuf.v1.FileSendService/SendFile"
)

// FileSendServiceClient is the client API for FileSendService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FileSendServiceClient interface {
	SendFile(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[SendFileRequest, SendFileResponse], error)
}

type fileSendServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFileSendServiceClient(cc grpc.ClientConnInterface) FileSendServiceClient {
	return &fileSendServiceClient{cc}
}

func (c *fileSendServiceClient) SendFile(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[SendFileRequest, SendFileResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &FileSendService_ServiceDesc.Streams[0], FileSendService_SendFile_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SendFileRequest, SendFileResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FileSendService_SendFileClient = grpc.ClientStreamingClient[SendFileRequest, SendFileResponse]

// FileSendServiceServer is the server API for FileSendService service.
// All implementations must embed UnimplementedFileSendServiceServer
// for forward compatibility.
type FileSendServiceServer interface {
	SendFile(grpc.ClientStreamingServer[SendFileRequest, SendFileResponse]) error
	mustEmbedUnimplementedFileSendServiceServer()
}

// UnimplementedFileSendServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFileSendServiceServer struct{}

func (UnimplementedFileSendServiceServer) SendFile(grpc.ClientStreamingServer[SendFileRequest, SendFileResponse]) error {
	return status.Error(codes.Unimplemented, "method SendFile not implemented")
}
func (UnimplementedFileSendServiceServer) mustEmbedUnimplementedFileSendServiceServer() {}
func (UnimplementedFileSendServiceServer) testEmbeddedByValue()                         {}

// UnsafeFileSendServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FileSendServiceServer will
// result in compilation errors.
type UnsafeFileSendServiceServer interface {
	mustEmbedUnimplementedFileSendServiceServer()
}

func RegisterFileSendServiceServer(s grpc.ServiceRegistrar, srv FileSendServiceServer) {
	// If the following call panics, it indicates UnimplementedFileSendServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FileSendService_ServiceDesc, srv)
}

func _FileSendService_SendFile_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(FileSendServiceServer).SendFile(&grpc.GenericServerStream[SendFileRequest, SendFileResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FileSendService_SendFileServer = grpc.ClientStreamingServer[SendFileRequest, SendFileResponse]

// FileSendService_ServiceDesc is the grpc.ServiceDesc for FileSendService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FileSendService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pbuf.v1.FileSendService",
	HandlerType: (*FileSendServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SendFile",
			Handler:       _FileSendService_SendFile_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "pair.proto",
}

const (
	ClipboardControlService_GetClipboard_FullMethodName = "/pbuf.v1.ClipboardControlService/GetClipboard"
	ClipboardControlService_SetClipboard_FullMethodName = "/pbuf.v1.ClipboardControlService/SetClipboard"
)

// ClipboardControlServiceClient is the client API for ClipboardControlService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ClipboardControlServiceClient interface {
	GetClipboard(ctx context.Context, in *GetClipboardRequest, opts ...grpc.CallOption) (*GetClipboardResponse, error)
	SetClipboard(ctx context.Context, in *SetClipboardRequest, opts ...grpc.CallOption) (*SetClipboardResponse, error)
}

type clipboardControlServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewClipboardControlServiceClient(cc grpc.ClientConnInterface) ClipboardControlServiceClient {
	return &clipboardControlServiceClient{cc}
}

func (c *clipboardControlServiceClient) GetClipboard(ctx context.Context, in *GetClipboardRequest, opts ...grpc.CallOption) (*GetClipboardResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetClipboardResponse)
	err := c.cc.Invoke(ctx, ClipboardControlService_GetClipboard_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clipboardControlServiceClient) SetClipboard(ctx context.Context, in *SetClipboardRequest, opts ...grpc.CallOption) (*SetClipboardResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetClipboardResponse)
	err := c.cc.Invoke(ctx, ClipboardControlService_SetClipboard_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ClipboardControlServiceServer is the server API for ClipboardControlService service.
// All implementations must embed UnimplementedClipboardControlServiceServer
// for forward compatibility.
type ClipboardControlServiceServer interface {
	GetClipboard(context.Context, *GetClipboardRequest) (*GetClipboardResponse, error)
	SetClipboard(context.Context, *SetClipboardRequest) (*SetClipboardResponse, error)
	mustEmbedUnimplementedClipboardControlServiceServer()
}

// UnimplementedClipboardControlServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedClipboardControlServiceServer struct{}

func (UnimplementedClipboardControlServiceServer) GetClipboard(context.Context, *GetClipboardRequest) (*GetClipboardResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetClipboard not implemented")
}
func (UnimplementedClipboardControlServiceServer) SetClipboard(context.Context, *SetClipboardRequest) (*SetClipboardResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetClipboard not implemented")
}
func (UnimplementedClipboardControlServiceServer) mustEmbedUnimplementedClipboardControlServiceServer() {
}
func (UnimplementedClipboardControlServiceServer) testEmbeddedByValue() {}

// UnsafeClipboardControlServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ClipboardControlServiceServer will
// result in compilation errors.
type UnsafeClipboardControlServiceServer interface {
	mustEmbedUnimplementedClipboardControlServiceServer()
}

func RegisterClipboardControlServiceServer(s grpc.ServiceRegistrar, srv ClipboardControlServiceServer) {
	// If the following call panics, it indicates UnimplementedClipboardControlServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ClipboardControlService_ServiceDesc, srv)
}

func _ClipboardControlService_GetClipboard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetClipboardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClipboardControlServiceServer).GetClipboard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClipboardControlService_GetClipboard_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClipboardControlServiceServer).GetClipboard(ctx, req.(*GetClipboardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClipboardControlService_SetClipboard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetClipboardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClipboardControlServiceServer).SetClipboard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClipboardControlService_SetClipboard_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClipboardControlServiceServer).SetClipboard(ctx, req.(*SetClipboardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ClipboardControlService_ServiceDesc is the grpc.ServiceDesc for ClipboardControlService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ClipboardControlService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pbuf.v1.ClipboardControlService",
	HandlerType: (*ClipboardControlServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetClipboard",
			Handler:    _ClipboardControlService_GetClipboard_Handler,
		},
		{
			MethodName: "SetClipboard",
			Handler:    _ClipboardControlService_SetClipboard_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pair.proto",
}
