import {
    VerticalBox,
    HorizontalBox,
    GridBox,
    ScrollView,
    Button,
} from "std-widgets.slint";

import { NodeStatus, Device, DeviceRelationship } from "models.slint";
import {
    Horizontal,
    Vertical,
    MaterialText,
    MaterialWindow,
    Switch,
    AppBar,
    SmallAppBar,
    Modal,
    ModalDrawer,
    Dialog,
    ScrollView,
    Icon,
    FilledButton,
    ModalBottomSheet,
    OutlinedCard,
    ElevatedCard,
    ActionChip,
    Icon,
    Grid,
    Drawer,
    OutlineButton,
    Badge,
} from "material/material.slint";
import { CheckBox } from "material/ui/components/check_box.slint";
import {
    CircularProgressIndicator,
} from "material/ui/components/progress_indicator.slint";
import {
    HorizontalDivider,
    VerticalDivider,
} from "material/ui/components/divider.slint";
import { Icons } from "material/ui/icons/icons.slint";
import { TonalButton } from "material/ui/components/tonal_button.slint";



component DeviceCard {
    in property <Device> device;
    callback clicked(Device);

    card := OutlinedCard {
        clickable: true;
        clicked => {
            root.clicked(device);
        }

        Badge {
            x: card.width - self.width - 10px;
            y: 10px;
            text: device.relationship == DeviceRelationship.paired ? "Paired" : device.relationship == DeviceRelationship.connected ? "Connected" : "Found";
        }

        Vertical {
            Horizontal {
                Rectangle {
                    height: 50px;
                    width: 50px;
                    background: device.color;
                    border-radius: 8px;
                    Icon {
                        source: @image-url("./icons/location.svg");
                        height: 100%;
                        width: 100%;
                    }
                }

                VerticalDivider { }

                Text {
                    text: device.name;
                    font-size: 30px;
                }
            }

            Grid {
                spacing-vertical: 0;
                spacing-horizontal: 30px;
                Row {
                    MaterialText {
                        text: "ID:";
                    }

                    MaterialText {
                        text: device.id;
                    }
                }

                Row {
                    MaterialText {
                        text: "Address:";
                    }

                    MaterialText {
                        text: device.address + ":" + device.port;
                    }
                }
            }
        }
    }
}

export component MainWindow inherits MaterialWindow {
    in property <NodeStatus> node_status: {
        running: false,
        okay: true,
    };
    in property <[Device]> devices: [
        {
            name: "jealomy",
            color: rgb(200, 100, 200),
            address:"192.192.192.192",
            port: 89291,
            id: "AF38FAF38FAF38FAF38FAF38FAF38F8F",
            relationship: DeviceRelationship.found,
        }
    ];
    callback request_pair(Device);
    property <Device> selected_device;

    width: 400px;
    height: 500px;

    Vertical {
        padding: 0;
        spacing: 0;
        AppBar {
            width: root.width;
            height: 50px;
            title: "Alat";

            leading_button: {
                icon: node_status.running ? Icons.check : Icons.remove,
                enabled: true,
            };
            leading_button_clicked => {
                node_drawer.show();
            };
            trailing_button: {
                icon: Icons.menu,
                enabled: true,
            };
        }

        ScrollView {
            for device in devices: DeviceCard {
                device: device;
                clicked(device) => {
                    if device.relationship == DeviceRelationship.found {
                        selected_device = device;
                        ask_pair_dialog.show();
                    }
                }
            }
        }
    }

    node_drawer := ModalDrawer {
        title: status.running ? "Node running" : "Node stopped";
        height: root.height;
        width: root.width;
        in property <NodeStatus> status: node_status;

        property <bool> switch_on: status.running;

        Horizontal {
            alignment: LayoutAlignment.space-between;
            MaterialText {
                text: switch_on ? status.running ? "Stop node" : "Starting node..." : status.running ? "Stopping node..." : "Start node";
                font-size: 18px;
            }

            if switch_on == status.running: Switch {
                checked: switch_on;
                checked_state_changed(checked) => {
                    switch_on = checked;
                }
            }
            if switch_on != status.running: CircularProgressIndicator {
                indeterminate: true;
            }
        }
    }

    in property <bool> is_pairing;
    in property <bool> pairing_succeded;
    in property <string> pairing_error;

    changed is_pairing => {
        pairing_modal.show();
    }
    changed pairing_succeded => {
        pairing_modal.show();
    }
    changed pairing_error => {
        pairing_modal.show();
    }

    pairing_modal := ModalBottomSheet {
        in property <Device> device: selected_device;
        width: root.width;
        height: root.height;

        Vertical {
            Horizontal {
                width: 100%;
                alignment: LayoutAlignment.center;

                if is_pairing: CircularProgressIndicator {
                    indeterminate: true;
                    width: 100px;
                    height: self.width;
                }
                if !is_pairing && pairing_succeded: Icon {
                    source: Icons.check;
                    width: 100px;
                    height: self.width;
                }
                if !is_pairing && !pairing_succeded: Icon {
                    width: 100px;
                    height: self.width;
                    source: Icons.close;
                }
            }

            Text {
                text: is_pairing ? "Pairing to " + device.name + "..." : pairing_succeded ? "Succesfully paired to " + device.name : "Error pairing to " + device.name + ": " + pairing_error;
            }
        }
    }

    ask_pair_dialog := Dialog {
        width: root.width;
        height: root.height;
        property <Device> device: selected_device;

        title: "Pair with \n" + device.name + "?";
        actions: ["Cancel"];
        default_action_text: "Pair";
        default_action_clicked => {
            request_pair(device);
        }
        action_clicked() => {
            ask_pair_dialog.close();
        }
    }
}
