import {
    VerticalBox,
    HorizontalBox,
    GridBox,
    ScrollView,
    Button,
} from "std-widgets.slint";

import { NodeStatus, Device, DeviceRelationship } from "models.slint";
import {
    Horizontal,
    Vertical,
    MaterialText,
    MaterialWindow,
    Switch,
    AppBar,
    SmallAppBar,
    Modal,
    ModalDrawer,
    Dialog,
    ScrollView,
    Icon,
} from "material/material.slint";
import { CheckBox } from "material/ui/components/check_box.slint";
import {
    CircularProgressIndicator,
} from "material/ui/components/progress_indicator.slint";
import {
    HorizontalDivider,
    VerticalDivider,
} from "material/ui/components/divider.slint";
import { OutlinedCard, ElevatedCard } from "material/ui/components/card.slint";
import { Icon } from "material/ui/components/icon.slint";
import { ActionChip } from "material/ui/components/chip.slint";
import { Grid } from "material/ui/components/grid.slint";
import { FilledButton } from "material/ui/components/filled_button.slint";
import { ModalBottomSheet } from "material/ui/components/bottom_sheet.slint";
import { Icons } from "material/ui/icons/icons.slint";
import { Drawer } from "material/ui/components/drawer.slint";



component DeviceCard {
    in property <Device> device;
    callback clicked(Device);

    card := OutlinedCard {
        clickable: true;

        if device.relationship == DeviceRelationship.found: FilledButton {
            x: card.width - self.width - 10px;
            y: 10px;
            text: "Pair";
            clicked => {
                clicked(device);
            }
        }

        Vertical {
            Horizontal {
                Rectangle {
                    height: 50px;
                    width: 50px;
                    background: device.color;
                    border-radius: 8px;
                    Icon {
                        source: @image-url("./icons/location.svg");
                        height: 100%;
                        width: 100%;
                    }
                }

                VerticalDivider { }

                Text {
                    text: device.name;
                    font-size: 30px;
                }
            }

            Grid {
                spacing-vertical: 0;
                spacing-horizontal: 30px;
                Row {
                    MaterialText {
                        text: "ID:";
                    }

                    MaterialText {
                        text: device.id;
                    }
                }

                Row {
                    MaterialText {
                        text: "Address:";
                    }

                    MaterialText {
                        text: device.address + ":" + device.port;
                    }
                }
            }
        }
    }
}

export component MainWindow inherits MaterialWindow {
    in property <NodeStatus> node_status: {
        running: false,
        okay: true,
    };
    in property <[Device]> devices: [
        {
            name: "jealomy",
            color: rgb(200, 100, 200),
            address:"192.192.192.192",
            port: 89291,
            id: "AF38FAF38FAF38FAF38FAF38FAF38F8F",
            relationship: DeviceRelationship.found,
        }
    ];
    callback request_pair(Device);
    property <Device> selected_device;

    width: 400px;
    height: 500px;

    Vertical {
        padding: 0;
        spacing: 0;
        AppBar {
            width: root.width;
            height: 50px;
            title: "Alat";

            leading_button: {
                icon: node_status.running ? Icons.check : Icons.remove,
                enabled: true,
            };
            leading_button_clicked => {
                node_drawer.show();
            };
            trailing_button: {
                icon: Icons.menu,
                enabled: true,
            };
        }

        ScrollView {
            for device in devices: DeviceCard {
                device: device;
                clicked(device) => {
                    selected_device = device;
                    device_dialog.show();
                }
            }
        }
    }

    node_drawer := ModalDrawer {
        title: status.running ? "Node running" : "Node stopped";
        height: root.height;
        width: root.width;
        in property <NodeStatus> status: node_status;

        property <bool> switch_on: status.running;

        Horizontal {
            alignment: LayoutAlignment.space-between;
            MaterialText {
                text: switch_on ? status.running ? "Stop node" : "Starting node..." : status.running ? "Stopping node..." : "Start node";
                font-size: 18px;
            }

            if switch_on == status.running: Switch {
                checked: switch_on;
                checked_state_changed(checked) => {
                    switch_on = checked;
                }
            }
            if switch_on != status.running: CircularProgressIndicator {
                indeterminate: true;
            }
        }
    }

    device_dialog := Dialog {
        width: root.width;
        height: root.height;
        property <Device> device: selected_device;

        title: "Pair with \n" + device.name + "?";
        actions: ["Cancel"];
        default_action_text: "Pair";
        default_action_clicked => {
            request_pair(device);
        }
        action_clicked(index) => {
            device_dialog.close();
        }
    }
}
