// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConfigReady() {
  return window['go']['app']['App']['ConfigReady']();
}

export function Run() {
  return window['go']['app']['App']['Run']();
}
