// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {color} from '../models';

export function ConfigReady():Promise<boolean>;

export function GetAlatColors():Promise<Array<color.Color>>;

export function Run():Promise<void>;

export function SettingsGetDeviceColor():Promise<string>;

export function SettingsGetDeviceName():Promise<string>;

export function SettingsSetDeviceColor(arg1:string):Promise<void>;

export function SettingsSetDeviceName(arg1:string):Promise<void>;
