// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {color} from '../models';
import {discovery} from '../models';
import {node} from '../models';
import {device} from '../models';
import {app} from '../models';
import {config} from '../models';

export function AskFileSharingDestDirectory():Promise<string>;

export function ConfigReady():Promise<boolean>;

export function GetAlatColors():Promise<Array<color.Color>>;

export function GetFoundDevices():Promise<Array<discovery.FoundDevice>>;

export function GetNodeStatus():Promise<node.Status>;

export function GetPairedDevices():Promise<Array<device.PairedDevice>>;

export function IsSearchingDevices():Promise<boolean>;

export function RequestPairingFoundDevice(arg1:string):Promise<app.RequestPairingResult>;

export function Run():Promise<void>;

export function SearchDevices():Promise<void>;

export function SettingsGetDeviceColor():Promise<string>;

export function SettingsGetDeviceName():Promise<string>;

export function SettingsGetFileSharingSettings():Promise<config.FileSharingSettings>;

export function SettingsGetFolderSyncSettings():Promise<config.FolderSyncSettings>;

export function SettingsGetMediaControlSettings():Promise<config.MediaControlSettings>;

export function SettingsGetNotificationSyncSettings():Promise<config.NotificationSyncSettings>;

export function SettingsGetRemoteInputSettings():Promise<config.RemoteInputSettings>;

export function SettingsGetUniversalClipboardSettings():Promise<config.UniversalClipboardSettings>;

export function SettingsSetDeviceColor(arg1:string):Promise<void>;

export function SettingsSetDeviceName(arg1:string):Promise<void>;

export function SettingsSetFileSharingSettings(arg1:config.FileSharingSettings):Promise<void>;

export function SettingsSetFolderSyncSettings(arg1:config.FolderSyncSettings):Promise<void>;

export function SettingsSetMediaControlSettings(arg1:config.MediaControlSettings):Promise<void>;

export function SettingsSetNotificationSyncSettings(arg1:config.NotificationSyncSettings):Promise<void>;

export function SettingsSetRemoteInputSettings(arg1:config.RemoteInputSettings):Promise<void>;

export function SettingsSetSetupComplete(arg1:boolean):Promise<void>;

export function SettingsSetUniversalClipboardSettings(arg1:config.UniversalClipboardSettings):Promise<void>;
