// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AskFileSharingDestDirectory() {
  return window['go']['app']['App']['AskFileSharingDestDirectory']();
}

export function ConfigReady() {
  return window['go']['app']['App']['ConfigReady']();
}

export function GetAlatColors() {
  return window['go']['app']['App']['GetAlatColors']();
}

export function Run() {
  return window['go']['app']['App']['Run']();
}

export function SettingsGetDeviceColor() {
  return window['go']['app']['App']['SettingsGetDeviceColor']();
}

export function SettingsGetDeviceName() {
  return window['go']['app']['App']['SettingsGetDeviceName']();
}

export function SettingsGetFileSharingSettings() {
  return window['go']['app']['App']['SettingsGetFileSharingSettings']();
}

export function SettingsSetDeviceColor(arg1) {
  return window['go']['app']['App']['SettingsSetDeviceColor'](arg1);
}

export function SettingsSetDeviceName(arg1) {
  return window['go']['app']['App']['SettingsSetDeviceName'](arg1);
}

export function SettingsSetFileSharingSettings(arg1) {
  return window['go']['app']['App']['SettingsSetFileSharingSettings'](arg1);
}
