// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AskFileSharingDestDirectory() {
  return window['go']['app']['App']['AskFileSharingDestDirectory']();
}

export function AskFilesSend(arg1) {
  return window['go']['app']['App']['AskFilesSend'](arg1);
}

export function ConfigReady() {
  return window['go']['app']['App']['ConfigReady']();
}

export function GetAlatColors() {
  return window['go']['app']['App']['GetAlatColors']();
}

export function GetConnectedDevices() {
  return window['go']['app']['App']['GetConnectedDevices']();
}

export function GetFoundDevices() {
  return window['go']['app']['App']['GetFoundDevices']();
}

export function GetNodeStatus() {
  return window['go']['app']['App']['GetNodeStatus']();
}

export function GetPairedDevices() {
  return window['go']['app']['App']['GetPairedDevices']();
}

export function Hide() {
  return window['go']['app']['App']['Hide']();
}

export function QueryDeviceSysInfo(arg1) {
  return window['go']['app']['App']['QueryDeviceSysInfo'](arg1);
}

export function Quit() {
  return window['go']['app']['App']['Quit']();
}

export function RequestPairingFoundDevice(arg1) {
  return window['go']['app']['App']['RequestPairingFoundDevice'](arg1);
}

export function Run() {
  return window['go']['app']['App']['Run']();
}

export function ServiceGetFileSendStatus() {
  return window['go']['app']['App']['ServiceGetFileSendStatus']();
}

export function ServiceStartSendFilesToDevice(arg1, arg2) {
  return window['go']['app']['App']['ServiceStartSendFilesToDevice'](arg1, arg2);
}

export function SettingsGetDeviceColorName() {
  return window['go']['app']['App']['SettingsGetDeviceColorName']();
}

export function SettingsGetDeviceName() {
  return window['go']['app']['App']['SettingsGetDeviceName']();
}

export function SettingsGetFileSend() {
  return window['go']['app']['App']['SettingsGetFileSend']();
}

export function SettingsGetSysInfo() {
  return window['go']['app']['App']['SettingsGetSysInfo']();
}

export function SettingsSetDeviceColorName(arg1) {
  return window['go']['app']['App']['SettingsSetDeviceColorName'](arg1);
}

export function SettingsSetDeviceName(arg1) {
  return window['go']['app']['App']['SettingsSetDeviceName'](arg1);
}

export function SettingsSetFileSend(arg1) {
  return window['go']['app']['App']['SettingsSetFileSend'](arg1);
}

export function SettingsSetSetupComplete(arg1) {
  return window['go']['app']['App']['SettingsSetSetupComplete'](arg1);
}

export function SettingsSetSysInfo(arg1) {
  return window['go']['app']['App']['SettingsSetSysInfo'](arg1);
}

export function Show() {
  return window['go']['app']['App']['Show']();
}
