// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';
import {color} from '../models';
import {connected} from '../models';
import {discovery} from '../models';
import {node} from '../models';
import {device} from '../models';
import {filesend} from '../models';
import {pbuf} from '../models';
import {config} from '../models';

export function AskFileSharingDestDirectory():Promise<string>;

export function AskFilesSend(arg1:string):Promise<Array<app.SendFile>>;

export function ConfigReady():Promise<boolean>;

export function GetAlatColors():Promise<Array<color.Color>>;

export function GetConnectedDevices():Promise<Array<connected.Connected>>;

export function GetFoundDevices():Promise<Array<discovery.FoundDevice>>;

export function GetNodeStatus():Promise<node.Status>;

export function GetPairedDevices():Promise<Array<device.PairedDevice>>;

export function RequestPairingFoundDevice(arg1:string):Promise<app.RequestPairingResult>;

export function Run():Promise<void>;

export function ServiceGetFileSendStatus():Promise<filesend.FileTransfersStatus>;

export function ServiceStartSendFilesToDevice(arg1:connected.Connected,arg2:Array<string>):Promise<void>;

export function ServiceSysInfoGet(arg1:connected.Connected):Promise<pbuf.SysInfo>;

export function SettingsGetDeviceColorName():Promise<string>;

export function SettingsGetDeviceName():Promise<string>;

export function SettingsGetFileSend():Promise<config.FileSendSettings>;

export function SettingsGetSysInfo():Promise<config.SysInfoSettings>;

export function SettingsSetDeviceColorName(arg1:string):Promise<void>;

export function SettingsSetDeviceName(arg1:string):Promise<void>;

export function SettingsSetFileSend(arg1:config.FileSendSettings):Promise<void>;

export function SettingsSetSetupComplete(arg1:boolean):Promise<void>;

export function SettingsSetSysInfo(arg1:config.SysInfoSettings):Promise<void>;
